# Include: pulls from production config without changing anything
# Override: patches sections from config or adds new sections

include:
  include_all: false # if true, includes all sections from production (can still override)

  # list of all sections (keys) to include from production verbatim
  include_these:
    - file_size_limit
    - file_type_ext
    - reporter_settings
    - feedback_notifier_settings
    - ai_completion_retry_protocol

  # custom specific pieces of production to include
  # list of the main attribute of the section (usually `name:`, but could be other things)
  containers:
    - name: stats-python-sandbox

  ducks:
    - name: stats-duck

  tools:
    - name: run_python


override:
  # sql is a dictionary of dictionaries, and so it adds the entire sql section but overrides the database dictionary
  sql:
    database: local-testing-configs/local.db

  # includes only the one container from production, but includes all settings except overrides mounts
  containers:
    - name: stats-python-sandbox
      mounts:
        - { source: datasets/, target: /home/sandbox/datasets/ }

  # Includes just the standard rubber duck and all of its production settings, modifying only the "engine" attribute
  ducks:
    - name: standard-rubber-duck
      settings:
        agent:
          engine: gpt-4.1-mini

  # could do the same for all sections of the production config

  servers:
    # If <server id> (int) exists in production, it includes and modifies its contents
    # If the id does not exist, it adds this as a new server
    "1058490579799003187":
      server_name: BeanLab
      channels:
        - channel_id: 1428518677287796756
          channel_name: Ducks/tyler-chat-bot
          timeout: 30
          ducks:
  #          - standard-rubber-duck
  #          - emoji-duck
            - stats-duck

  admin_settings:
    admin_channel_id: 1429899217890967663
    admin_role_id: 1149033209821134858