sql:
  db_type: sqlite
  database: local-testing-configs/local_reese_database.db

containers: { }

tools: { }


# include one duck without overrides ($include doesn't copy in the key
ducks:
  standard-rubber-duck:
    $include: production-config.yaml:$.ducks.standard-rubber-duck

# override usage
ducks:
  standard-rubber-duck:
    $include: production-config.yaml:$.ducks.standard-rubber-duck
    settings:
      agent:
        engine: gpt-5-nano

# include all ducks with example override
ducks:
  $include: production-config.yaml:$.ducks
  standard-rubber-duck:
    settings:
      agent:
        engine: gpt-5-nano

# include multiple specific ducks
ducks:
  standard-rubber-duck:
    $include: production-config.yaml:$.ducks.standard-rubber-duck
  stats-duck:
    $include: production-config.yaml:$.ducks.stats-duck


servers:
  BeanLab:
    server_id: 1058490579799003187
    channels:
      Ducks/tyler-chat-bot:
        channel_id: 1428518677287796756
        timeout: 300
        duck:
          standard-rubber-duck

      Ducks/tyler-ta-channel:
        channel_id: 1466558248726560880
        timeout: 300
        duck:
          Conversation-Review:
            duck_type: conversation_review
            settings:
              target_channel_ids:
                - 1428518677287796756

$include: production-settings.yaml:$.general_settings

admin_settings:
  admin_channel_id: 1429899217890967663
  admin_role_id: 1149033209821134858