sql:
  database: local-testing-configs/local_reese_database.db

containers: { }

tools: { }


# include one duck without overrides
ducks:
  standard-rubber-duck:
    $include: production-config.yaml:$.ducks.standard-rubber-duck


## include one duck with overrides
#ducks:
#  standard-rubber-duck:
#    $include: production-config.yaml:$.ducks.standard-rubber-duck
#    settings:
#      agent:
#        engine: gpt-5-nano
#
## include all ducks (no overrides)
#ducks:
#  $include: production-config.yaml:$.ducks
#
## include multiple specific ducks (no overrides)
#ducks:
#  standard-rubber-duck:
#    $include: production-config.yaml:$.ducks.standard-rubber-duck
#  stats-duck:
#    $include: production-config.yaml:$.ducks.stats-duck


servers:
  BeanLab:
    server_id: <id>
    channels:
      Ducks/tyler-chat-bot:
        channel_id: <id>
        timeout: 300
        duck:
          standard-rubber-duck

      Ducks/tyler-ta-channel:
        channel_id: <id>
        timeout: 300
        duck:
          Conversation-Review:
            duck_type: conversation_review
            settings:
              target_channel_ids:
                - <id>

admin_settings:
  admin_channel_id: <id>
  admin_role_id: <id>